### ISSUE TITLE
[Error] You may need an additional loader to handle the result of these loaders.

### ISSUE THREAD

**Issue by disinibale** [themeselection/materio-vuetify-vuejs-admin-template-free#11]
### Steps to reproduce

yarn serve

### What is expected?

Application Running

### What is actually happening?

Error producing 
Module parse failed: Unexpected token (806:65)
File was processed with these loaders:
 * ./node_modules/cache-loader/dist/cjs.js
 * ./node_modules/babel-loader/lib/index.js
 * ./node_modules/cache-loader/dist/cjs.js
 * ./node_modules/vue-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|     // add message template
|     async saveMessageTemplate() {
>       this.formAddTemplate.attachments = this.$refs['uppy-data']?.uppy?.getFiles();
|       this.on_reply_message.attachments = this.$refs['uppy-data-onreply']?.uppy?.getFiles();
|       this.formAddTemplate.id = uuidv4();

 @ ./src/components/dialog/message_template/message_template.vue?vue&type=script&lang=js& 1:0-309 1:325-328 1:330-636 1:330-636
 @ ./src/components/dialog/message_template/message_template.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--13-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/message-template/index.vue?vue&type=script&lang=js&
 @ ./src/views/message-template/index.vue?vue&type=script&lang=js&
 @ ./src/views/message-template/index.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.31.98:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

### NodeJS Version

v16.14.2

### Package manager name & version

Yarn 1.22.17

### Browser name & version

Chrome Version 103.0.5060.53

### Device on which you tested

Windows Pro 10

**Comment by tomerpeled** [comment]
I also encountering this error

**Comment by Dan030** [comment]
me too

**Comment by tomerpeled** [comment]
Any updates how to solve it?
I also purchased the versions that costs money and still encountering the same issue

**Comment by Dan030** [comment]
babel.config.js --->

module.exports = {
  presets: ["@vue/cli-plugin-babel/preset"],
  plugins: [
    "@babel/plugin-proposal-nullish-coalescing-operator",
    "@babel/plugin-proposal-optional-chaining"
  ]
};

**Comment by tomerpeled** [comment]
@Dan030 Cool!
That works, thanks!

**Comment by jd-solanki** [comment]
Here are some common solutions for installation issues:
- Make sure to use Node LTS
- Use yarn or run npm install with `npm install --legacy-peer-deps`
- Don't delete the lock file, use it
- Remove node_modules and run the installation again

@disinibale Please let us know if your issue is not resolved
