### ISSUE TITLE
I found that vue2.6 was used in the project, and then because I wanted to use Vue's API, I integrated @ Vue / composition API in the warehouse. Have you considered directly exporting vue3's version?

### ISSUE THREAD

**Issue by XiaoRIGE** [themeselection/materio-vuetify-vuejs-admin-template-free#12]
### What problem does this feature solve?

We can use the latest syntax of vue3

### What does the proposed solution look like?

Use vue3 as the underlying framework to build the page

**Comment by jd-solanki** [comment]
Hi @XiaoRIGE 

We are now using vue 3 composition API. Now, you can use latest syntax including script setup in our template.

Thanks for raising the issue.

**Comment by XiaoRIGE** [comment]
thanks!
