### ISSUE TITLE
In the calendar, when creating a new event by clicking on a date space, the default date inputted is wrong

### ISSUE THREAD

**Issue by ibiza240** [themeselection/materio-vuetify-vuejs-admin-template-free#14]
### Steps to reproduce

1. Go to https://demos.themeselection.com/materio-vuetify-vuejs-admin-template/demo-1/calendar (Login as admin)
2. Change the view to Weekly time
3. Click on a date space (e.g. when I tested, 2022-11-30 10:00 AM)

### What is expected?

The date displayed in the "Start date" field on the right-side panel to be the same as the date space clicked.

### What is actually happening?

The date displayed in the "Start date" field on the right-side panel does not correspond to the date space clicked.

For instance, I got "2022-09-30 00:00" after clicking on the date space (step 3).

**Comment by jd-solanki** [comment]
Hi @ibiza240,

Please raise the issue at the materio pro repo for getting premium product support. Our technical team regularly responds to the queries there.

You can check support page for raising support: https://themeselection.com/support/

Thanks for getting in touch with us.

Happy coding 🙌🏻
