### ISSUE TITLE
Pro version shows a blank page on localhost

### ISSUE THREAD

**Issue by assistivai** [themeselection/materio-vuetify-vuejs-admin-template-free#16]
### Steps to reproduce

Hello, I bought the pro version of Materio template in Vue 2. I got the upgrade and download link for Vue 3 version, but now when I try to run the project, I see the loader screen and then nothing [Blank Screen]. This free version loads up.

I have tried so many times to contact the team and get access to the paid version's Git Hub but haven't gotten any response. I need to get this to work as soon as possible. Please let me know who I can get it to touch with.

### What is expected?

Dev server loading up the index page on localhost

### What is actually happening?

Loader screen and then blank. The vue page is not loading up.

**Comment by jd-solanki** [comment]
Hi @assistivai 

Please raise the issue at materio pro repo for getting premium product support. Our technical team regularly responds to the queries there.

Thanks for getting in touch with us.

Happy coding 🙌🏻

**Comment by jd-solanki** [comment]
You can check support page for raising support: https://themeselection.com/support/
