### ISSUE TITLE
Can I skip vue and just use the css resources in it?

### ISSUE THREAD

**Issue by monicfenga** [themeselection/materio-vuetify-vuejs-admin-template-free#17]
### What problem does this feature solve?

Can be integrated with other frameworks and/or technologies

### What does the proposed solution look like?

As the title suggests. I thought Materio had a great look and wanted to use it in my own (blog) project, but I don't know how to use vue, so I wanted to use PHP to generate the page.

I just want to use the CSS part of it.

Is this feasible?

> Sorry for my bad english.

**Comment by jd-solanki** [comment]
Hi,

Thanks for raising the issue. As materio using Vuetifu - Vue component library, You have to use vue. You can't just use CSS from it. We suggest you better go with [UnoCSS](https://github.com/unocss/unocss), [Tailwind](https://tailwindcss.com/) or [Bootstrap](https://getbootstrap.com/) for CSS.

Happy coding 🙌🏻
