### ISSUE TITLE
Vuetify Anchor import error in UserProfile.vue - Typescript-version

### ISSUE THREAD

**Issue by moeezsaiyam** [themeselection/materio-vuetify-vuejs-admin-template-free#18]
### Steps to reproduce

After installing dependencies, run `npm run typecheck` or open the VsCode and go to UserProfile.vue, an error will be highlighted on line 02

### What is expected?

- Anchor type should be imported from module 'vuetify/lib/components'
- `npm run typecheck` command should run successfully

### What is actually happening?

Error in UserProfile.vue on line 02: _Cannot find module 'vuetify/lib/components' or its corresponding type declarations_ while importing type Anchor

### Additional data

NodeJS Version: v18.13.0
Package manager(npm|yarn|pnpm): npm 8.19.3
System: Mac M1 2020

**Comment by jd-solanki** [comment]
Thanks for raising the issue. We are planning to upgrade the free version soon, We will address this issue with that update.

Thanks for raising the issue.

Happy coding 🙌🏻

**Comment by jd-solanki** [comment]
I guess this is resolved now, Closing. Feel free to reopen if you have any further query.
