### ISSUE TITLE
Using the template in Nuxt

### ISSUE THREAD

**Issue by hendra-hartono** [themeselection/materio-vuetify-vuejs-admin-template-free#2]
I have an issue in getting this template working in my Nuxt Project (nuxt with vuetify).
How to :
- include the sass and scss files
- default preset template is not found in Vuetify module
- mdi js is not working

Please assist, many thanks

**Comment by jd-0001** [comment]
As Admin templates are meant for backend and it doesn't require SEO we didn't provide support for NuxtJS. If you want to integrate NuxtJS in our template please consider checking some online articles on how to migrate VueJS project to NuxtJS.

Here's some of what we have found:

[Official NuxtJS Docs](https://nuxtjs.org/)
[How to migrate a VueJs project to NuxtJS in 8 steps](https://dev.to/ngranja19/how-to-migrate-a-vuejs-project-to-nuxtjs-in-8-steps-41dm)

Can you please let us know why you want Nuxt in admin panel?

**Comment by cappuccinonet** [comment]
@jd-0001 I would be interested in a NuxtJS version of this awesome Materio template, too.

**Comment by jd-0001** [comment]
@cappuccinonet Can you please let us know why you want Nuxt in the admin panel?

We are already receiving lots of request for Nuxt in our [Vuexy Admin Template](https://themeforest.net/item/vuexy-vuejs-html-laravel-admin-dashboard-template/23328599) but we are unable to find out why people want nuxt in the admin panel.

We are thinking that admin panel don't require SEO and hence doesn't need nuxt.

If anyone wants nuxt please let us your requirement for nuxt so we understand and will think on that.

Regards.

**Comment by cappuccinonet** [comment]
@jd-0001 Nuxt, as far as I see it, has much more to offer than just adding some SEO friendly features to Vue.js. Some advantages are:
- You get great project structure by default (components, layouts, pages, store)
- It has an easy (partly automated) routing configuration
- There is an automated code optimization - which is great for speed
- You have more flexibility - render static or non static, etc.

Josh Deletener from Nuxt Nation masteringnuxt.com has some good blog articles about this:  
- https://masteringnuxt.com/blog/6-reasons-to-use-nuxt-for-your-next-project-in-2021
- https://masteringnuxt.com/blog/nuxt-server-side-rendering-vs-pre-rendering

Check out the intro chapter for Maximilian Schwarzenmüllers video course "Nuxt.js - Vue.js on Steroids", too. You may find it here  
- https://pro.academind.com/p/nuxt-js-vue-js-on-steroids or here 
- https://learning.oreilly.com/videos/nuxt-js-vue-js/9781789957396/

Anyways, I really miss your theme in this list ;-)
https://nuxtjs.org/themes

Kind regards

**Comment by jd-0001** [comment]
Hi Everyone,

Once vuetify will be in BETA we will start working on it. We will surely consider NuxtJS support in Vue 3 + Vuetify 3.

Till then if anyone has any resources which provide VueJS Only & Nuxt both versions please let us know. This will help in deciding the best approach.

With the current implementation, if we provide Vue only version then we won't be able to provide NuxtJS version and if we provide nuxtJS version then people who don't know NuxtJS won't able to use this template. So, please let us know if there is any middle ground where we can serve both kinds of developers.

Regards.

**Comment by changfeng2021** [comment]
The theme is beautiful, I also want to use it in Nuxt

**Comment by vinstah** [comment]
I'm using vuetify in nuxt already so will look at integrating this project

**Comment by jugurtha114** [comment]
it will be so great to add NuxtJS support !

**Comment by Haythamasalama** [comment]
I have a Vuexy theme,and i wanna migrate it to Nuxt 3 but the documentation does not have clear steps.

how to transfer @core, @layout, layouts, style, etc.

**Comment by jd-solanki** [comment]
Hi @Haythamasalama 

We don't support nuxt ATM and don't have any guide to migrate our template to nuxt. We do have plans for nuxtjs but there's no timeline on when it will be implemented. In meantime, We request you to create fresh nuxtjs project and slowly and carefully move components, pages, etc to nuxt version.

Happy coding 🙌🏻

**Comment by Phesky** [comment]
Hi everyone,

I'm interested in purchasing a Materio Multiple Use license. The license costs $129, and i don't know maybe it won't allows me to use the Materio components in any number of end products. I won't be able to charge end users for the Materio components, but I can charge my customers for my services ?. I'm not sure if I can use the Materio Multiple Use license for B2B purposes. The Materio license terms say that I can't use the license for more than one organization. However, I'm not sure if this applies to B2B customers.

**Comment by Phesky** [comment]
> Hi @Haythamasalama
> 
> We don't support nuxt ATM and don't have any guide to migrate our template to nuxt. We do have plans for nuxtjs but there's no timeline on when it will be implemented. In meantime, We request you to create fresh nuxtjs project and slowly and carefully move components, pages, etc to Nuxt version.
> 
> Happy coding 🙌🏻

**Comment by tdoan2010** [comment]
Did anyone successfully use this theme with Nuxt 3?

**Comment by jd-solanki** [comment]
We are working on nuxt version of our pro template and just after that we are releasing free nuxt version of materio in next 2-3 months. You can follow our twitter handle to latest updates: [Theme_Selection](https://twitter.com/Theme_Selection)

**Comment by jd-solanki** [comment]
✨ Released, Checkout the repo [here](https://github.com/themeselection/materio-vuetify-nuxtjs-admin-template-free)

![celebrate-in-love-gif-by-max](https://github.com/themeselection/materio-vuetify-vuejs-admin-template-free/assets/47495003/1053a1db-b0b0-4b19-9ec3-beead8e2319c)
