### ISSUE TITLE
SCSS and another templates not loading when change routes default page

### ISSUE THREAD

**Issue by macieleustaquio** [themeselection/materio-vuetify-vuejs-admin-template-free#21]
### Steps to reproduce

import { createRouter, createWebHistory } from 'vue-router'

const router = createRouter({
  history: createWebHistory(import.meta.env.BASE_URL),
  routes: [
    // ...setupLayouts(routes),
    {
      path: "/",
      name: "login",
      component: () => import ("@/layouts/components/Login.vue")
    }

  ],
  scrollBehavior() {
    return { top: 0 }
  },
})

export default router

### What is expected?

I expected the login page to load the same as the template

### What is actually happening?

When I change the theme's default homepage to the login page, the template and scss are not loaded.

**Comment by jd-solanki** [comment]
Styles are applied when layout classes are present as written here: https://github.com/themeselection/materio-vuetify-vuejs-admin-template-free/blob/main/typescript-version/src/layouts/blank.vue#L11

Please wrap your login page with those classes (most probably `layout-blank`) and it should work as expected.
