### ISSUE TITLE
trouble real requests

### ISSUE THREAD

**Issue by WayUltimaMilha** [themeselection/materio-vuetify-vuejs-admin-template-free#22]
### What problem does this feature solve?

Please, I have a question, I realized that the requests are a mock, how could I disable this mock and be able to test triggering the real requests?

### What does the proposed solution look like?

how could i disable mock and test on real requests?

**Comment by DeepKumbhare85** [comment]
Hello @WayUltimaMilha ,
Please don't create duplicate issues. Your issue has already been answered at : https://github.com/themeselection/materio-vuetify-vuejs-laravel-admin-template-free/issues/5

~Regards
