### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by ZeroNilZero** [themeselection/materio-vuetify-vuejs-admin-template-free#28]
### What problem does this feature solve?

as the [document](https://demos.themeselection.com/materio-vuetify-vuejs-admin-template/documentation/guide/getting-started/rtl.html#changing-direction-to-rtl) said for RTL: 

> For changing direction to RTL just set app.isRtl in theme config to true

but I couldn't find it. dose anyone succeeded to use RTL?

tried to manually set it to RTL, but the drawer menu came in middle of page on mobile devices and don't act as it should be.

### What does the proposed solution look like?

RTL Support

**Comment by DeepKumbhare85** [comment]
Hello @ZeroNilZero ,

Thank you for getting in touch with us. 

We offer RTL support exclusively in our pro version of the template. As for this free version, theme configuration options are not available. If you wish to access RTL support and additional features, we recommend purchasing the pro version of the template from the following link: https://themeselection.com/item/materio-vuetify-vuejs-admin-template/

~ Best Regards

**Comment by Phesky** [comment]
Hi everyone,

I'm interested in purchasing a Materio Multiple Use license. The license costs $129, and i don't know maybe it  won't allows me to use the Materio components in any number of end products. I won't be able to charge end users for the Materio components, but I can charge my customers for my services ?. I'm not sure if I can use the Materio Multiple Use license for B2B purposes. The Materio license terms say that I can't use the license for more than one organization. However, I'm not sure if this applies to B2B customers.

**Comment by ZeroNilZero** [comment]
why not offer the RTL as free sample and the LTR as pro!! 😕
