### ISSUE TITLE
Autorouting not working

### ISSUE THREAD

**Issue by buzzdev** [themeselection/materio-vuetify-vuejs-admin-template-free#29]
### Steps to reproduce

1. Get the source code by cloning it from github
2. cd ```javascript-version``` or ```typescript-version```
3. run ```pnpm install```
4. run ```pnpm dev```
5. Follow the documentation at https://demos.themeselection.com/materio-vuetify-vuejs-admin-template/documentation/guide/how-to-create-a-new-page.html

<img width="970" alt="image" src="https://github.com/themeselection/materio-vuetify-vuejs-admin-template-free/assets/6644151/ebf8d9ae-3b12-4217-97fd-32050baf6c33">

### What is expected?

Expected result: Creating a new .vue file, placed into the ```src/pages/``` folder would automatically generate a route.

### What is actually happening?

Error 404 - Page not found

<img width="1614" alt="image" src="https://github.com/themeselection/materio-vuetify-vuejs-admin-template-free/assets/6644151/0393c0b8-8fa3-4d74-86e6-a59ce867ab75">

### Additional data

**NodeJS Version:** v20.13.1
**Package manager:** pnpm
**Browser name & version:** Chrome 125.0.6422.113 (Official Build) (x86_64)
**System:** MacOS 11.7.10

**Comment by yagnikvamja** [comment]
Hello @buzzdev,

Thank you for contacting us.

The file-based routing feature is included in the pro version of our template. In the free version, routes must be configured manually.

Please feel free to check out our **Materio Pro** version: https://themeselection.com/item/materio-vuetify-vuejs-admin-template/

**Comment by buzzdev** [comment]
OK, thank you for the info.
Perhaps it would make sense to mention it on that doc page, if it's not already there ;)

**Comment by hariidavinci** [comment]
Ill have to agree with @buzzdev on mentioning it within the documentation page if there's a difference between the pro vs free. 

Im currently testing it out to see the benefits of using using this theme but i notice a few other things are missing like themeConfig.ts. 

It just makes it a little bit harder to evaluate between the free or the paid version. That aside, the theme is pretty decent!

**Comment by icangku** [comment]
i have pro version but still not working on dynamic file. created [id].vue make an error no matched for

**Comment by DeepKumbhare85** [comment]
Hello @buzzdev & @hariidavinci, 

Thank you for your suggestion. We will try to mention the differences in our upcoming release. 

Thanks a lot.

**Comment by DeepKumbhare85** [comment]
Hello @icangku, 

Thank you for the response. 

If you are a Pro user and facing the issue, please feel free to create a new issue on [Materio vuejs pro admin template](https://github.com/themeselection/materio-vuetify-vuejs-admin-template)

Thanks a lot.

~Best Regards.
