### ISSUE TITLE
Showing nothing after build

### ISSUE THREAD

**Issue by mostafa-rahmani** [themeselection/materio-vuetify-vuejs-admin-template-free#4]
After running the build command and serving the projects the public path can not be resolved so the components assets are not loaded.

**Comment by jd-0001** [comment]
Hi @mostafa-rahmani 

We have added `publicPath` conditionally based on your current environment.

Use `publicPath: '/'` if you are deploying your app to root of the domain. If you are going to deploy your app in subpath (i.e. `https://domain.com/my-sub-path/vue-app`) then just update `publicPath` as below:

```diff
- publicPath: process.env.NODE_ENV === 'production' ? '/demo/materio-vuetify-vuejs-admin-template-free/demo' : '/',
+ publicPath: process.env.NODE_ENV === 'production' ? '<sub-path>' : '/',
```
