### ISSUE TITLE
webpack to vitejs

### ISSUE THREAD

**Issue by kurob1993** [themeselection/materio-vuetify-vuejs-admin-template-free#6]
in advance I thank you, this is a beautiful template admin,

I was traumatized when using webpack on a large project.

is it possible to switch from webpack to vitejs?

**Comment by mostafa-rahmani** [comment]
I think It's a great idea. I'll try to test that and see if it's ok for a pull request

**Comment by jd-0001** [comment]
At the time we started developing [Materio Pro](https://themeselection.com/demo/materio-vuetify-vuejs-admin-template/landing) we didn't consider Vite and we didn't know about the support of Vuetify 2 + Vite so we chose good old Vue CLI.

However, we will surely update materio w/ vite in Vue 3 update.

**Comment by kingyue737** [comment]
I made a Vuetify 2 admin template with Vite https://github.com/kingyue737/vitify-admin. Maybe helpful to you for migrating materio.

**Comment by jd-solanki** [comment]
Hi all 👋🏻

Sorry for being late to the party. Materio's latest version now uses vite so I'm closing this.
