### ISSUE TITLE
why is everything deprecated?

### ISSUE THREAD

**Issue by ekrembiler** [themeselection/materio-vuetify-vuejs-admin-template-free#8]

**Comment by jd-0001** [comment]
Hi,

The warnings you are receiving while installing are from the libraries/packages we used.

We always keep our packages up to date when we make a major release. However, the writer of that package may use an older dependency that is no longer maintained for backward compatibility or any other code-related issue. But, that's not an issue. Those packages will work fine with our template.

Even if you like to try you can install these packages in the fresh VueJS project without our template and you will get the same.

**Comment by jd-0001** [comment]
Hi,

I updated the issue title so others can easily search for it and identify the issue.
